{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "web_app.fullname" . }}
  labels:
    {{- include "web_app.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "web_app.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
  behavior: 
    {{- range .Values.autoscaling.scaleDown }}
    scaleDown:
      stabilizationWindowSeconds: {{ .stabilizationWindowSeconds }}
      policies:
      - type: Percent
        value: {{ .value }}
        periodSeconds: {{ .periodSeconds }}
    {{- end }}
    {{- range .Values.autoscaling.scaleUp }}
    scaleUp:
      stabilizationWindowSeconds: {{ .stabilizationWindowSeconds }}
      policies:
      - type: Percent
        value: {{ .value }}
        periodSeconds: {{ .periodSeconds }}
    {{- end }}
{{- end }}
