apiVersion: v1
kind: Service
metadata:
  name: {{ include "web_app.fullname" . }}
  labels:
    {{- include "web_app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ext_service.type }}
  ports:
    - port: {{ .Values.ext_service.port }}
      targetPort: {{ .Values.ext_service.targetPort }}
      nodePort: {{ .Values.ext_service.nodePort }}
      protocol: TCP
      name: http
    - port: 22
      target Port: 22
      nodePort: {{ .Values.ssh.nodePort }}
     
  {{- with .Values.frontendLabels }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
