apiVersion: v1
kind: Service
metadata:
  name: {{ include "web_app.fullname" . }}
  labels:
    {{- include "web_app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  {{- with .Values.backendLabels }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}